### ISSUE TITLE
Touches not cancelled through DrawerController open pan

### ISSUE THREAD

**Issue by Jpoliachik** [wix/react-native-controllers#28] opened 2016-03-24 20:29 UTC
If you run the example for MMDrawerController, you'll notice that if you begin to highlight a cell then pan sideways to open the drawer menu, the initial cell highlight touch is cancelled and the cell does not get selected. 

This does not happen when using a the drawer here. It seems like a minor issue, but its actually VERY annoying when the center view is a List of selectable items. I accidentally 'select' a cell almost every time I mean to open the drawer. 

I believe it has something to do with react-native's gesture responder system. I haven't dug too deeply - but I'm assuming the initial press is still being handled by react-native and never gets cancelled, since MMDrawerContainer's PanGesture cancels touches natively, but RN is not aware of this. 

Is anyone more knowledgeable about the RN's gesture responder system and could explain this a bit more? I'm not sure the best place to begin digging here.

**Comment by talkol** [comment] 2016-03-25 00:55
@gran33 is working on a sprint of drawer features, let's try to have this one in there too
some of his work in progress:
https://github.com/wix/react-native-controllers/commit/b56266a63a6afed15f204739534f744a9ef60cbb
https://github.com/wix/react-native-controllers/commit/40c5a2caee98258a34ebbe7dfafd726f94faf528

**Comment by gran33** [comment] 2016-04-08 16:07
Please see the progress in pull request #38

**Comment by Jpoliachik** [comment] 2016-05-09 12:36
@gran33 Any update on when the changes in #38 will get merged?

**Comment by gran33** [comment] 2016-05-09 12:49
@Jpoliachik Work in progress, it might take some time.
If you have a solution you are welcome to PR.

**Comment by Jpoliachik** [comment] 2016-05-12 20:50
I'm working on cancelling the center view's touches while panning to open the drawer. 
Does anyone know how to cancel touches in RN? It looks like on the iOS side, toggling `userInteractionEnabled` does not work. Is there an explicit way to try this on the RN side? Re-rendering with `pointerEvents={'none'}` does not work.

**Comment by DanielZlotin** [comment] 2016-08-23 16:23
Closing, duplicate of #18

**Closed as completed by DanielZlotin** 2016-08-23 16:23 UTC
Labels: Implement before migrating
